### ISSUE TITLE
A bug in ui_test occurred

### ISSUE THREAD

**Issue by RalfJung** [oli-obk/ui_test#124]
I have a test with "got exit status: 101, but expected 1", and somehow that then leads to ui_test itself panicking:
```
tests/fail/dangling_pointers/dangling_pointer_addr_of.rs FAILED:
command: "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools-bin/miri" "--error-format=json" "-Dwarnings" "-Dunused" "-Zui-testing" "--target" "x86_64-unknown-linux-gnu" "--extern" "getrandom=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-6b8f3222aeffe636.rlib" "--extern" "getrandom=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-6b8f3222aeffe636.rmeta" "--extern" "getrandom_1=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-9cd0361dc160e129.rlib" "--extern" "getrandom_1=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libgetrandom-9cd0361dc160e129.rmeta" "--extern" "libc=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-9f24fb5ae7330c0d.rlib" "--extern" "libc=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/liblibc-9f24fb5ae7330c0d.rmeta" "--extern" "num_cpus=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libnum_cpus-946f1ead0dcf813c.rlib" "--extern" "num_cpus=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libnum_cpus-946f1ead0dcf813c.rmeta" "--extern" "rand=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/librand-fad150f794d27bf4.rlib" "--extern" "rand=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/librand-fad150f794d27bf4.rmeta" "--extern" "page_size=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libpage_size-2b1e5b87348e7f76.rlib" "--extern" "page_size=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libpage_size-2b1e5b87348e7f76.rmeta" "--extern" "tokio=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libtokio-ee90965d4570c1ab.rlib" "--extern" "tokio=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps/libtokio-ee90965d4570c1ab.rmeta" "--extern" "miri_test_deps=/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/miri-test-deps" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/syn-962486b45b77e21b" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/libc-9c87aa1293fc5ef6" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug/deps" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/parking_lot_core-6a8cb08b4c078874" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/deps" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/tokio-e265de171d766716" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/proc-macro2-9e396b1d0f0a1dcd" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/memchr-ef51a5410fa71c01" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/quote-cb4b74f9d230b053" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/getrandom-f656e41416722cf8" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/x86_64-unknown-linux-gnu/debug" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/lock_api-c5a9061826cbd40c" "-L" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui/miri/debug/build/log-9528da10329ca66c" "--out-dir" "/home/r/src/rust/rustc/build/x86_64-unknown-linux-gnu/stage0-tools/ui" "tests/fail/dangling_pointers/dangling_pointer_addr_of.rs" "-Zmiri-disable-alignment-check" "-Zmiri-disable-stacked-borrows" "-Zmiri-disable-validation" "--edition" "2021"



fail test got exit status: 101, but expected 1


A bug in `ui_test` occurred: test panicked: stderr:
thread 'main' panicked at 'this should never print: 0x24048', tests/fail/dangling_pointers/dangling_pointer_addr_of.rs:11:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

stdout:


full stderr:


FAILURES:
    tests/fail/dangling_pointers/dangling_pointer_offset_underscore.rs
    tests/fail/dangling_pointers/dyn_size.rs
    tests/fail/dangling_pointers/null_pointer_write_zst.rs
    tests/fail/dangling_pointers/dangling_pointer_addr_of.rs

test result: FAIL. 4 tests failed, 21 tests passed, 0 ignored, 0 filtered out
Error: 
   0: tests failed

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: <color_eyre[b15ccabfa4fd8674]::config::EyreHook>::default<unknown>
      at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/color-eyre-0.6.2/src/config.rs:1038
   2: <color_eyre[b15ccabfa4fd8674]::config::EyreHook>::into_eyre_hook::{closure#0}<unknown>
      at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/color-eyre-0.6.2/src/config.rs:1094
   3: eyre[36be82ca0e4c5a91]::capture_handler<unknown>
      at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eyre-0.6.8/src/lib.rs:605
   4: <eyre[36be82ca0e4c5a91]::Report>::from_adhoc::<&str><unknown>
      at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eyre-0.6.8/src/error.rs:110
   5: ui_test[74be05d767a4034a]::run_tests_generic::<compiletest[eb69efabcef4150c]::run_tests::{closure#1}, compiletest[eb69efabcef4150c]::run_tests::{closure#2}, (alloc[248d8bc8bed68184]::boxed::Box<dyn ui_test[74be05d767a4034a]::status_emitter::StatusEmitter + core[71ce68b5d36e54f1]::marker::Send>, ui_test[74be05d767a4034a]::status_emitter::Gha<false>)><unknown>
      at /home/r/.cargo/registry/src/index.crates.io-6f17d22bba15001f/ui_test-0.11.7/src/lib.rs:282
   6: compiletest[eb69efabcef4150c]::run_tests<unknown>
      at /home/r/src/rust/rustc/src/tools/miri/tests/compiletest.rs:144
   7: compiletest[eb69efabcef4150c]::ui<unknown>
      at /home/r/src/rust/rustc/src/tools/miri/tests/compiletest.rs:235
   8: compiletest[eb69efabcef4150c]::main<unknown>
      at /home/r/src/rust/rustc/src/tools/miri/tests/compiletest.rs:264
```

**Comment by RalfJung** [comment]
I think this is no longer an issue in current versions.
